name: Delete CloudFormation Stack

on:
  workflow_dispatch:   # Run manually from GitHub Actions UI

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Delete CloudFormation Stack
      run: |
        aws cloudformation delete-stack --stack-name three-tier-stack

    - name: Wait for stack deletion
      run: |
        aws cloudformation wait stack-delete-complete --stack-name three-tier-stack
